### ISSUE TITLE
Sketch 3.83 - Sketch Palettes file released June 16 cannot load any new palettes

### ISSUE THREAD

**Issue by mulvi** [andrewfiorillo/sketch-palettes#25]
Hi,

thank you so much for creating this plugin and being so responsive on twitter and github. I am using sketch version 3.83 on a mac 10.11.5 (both updated to latest versions) and the latest version of the plugin. 

When I try to load a color palette into global or document colors using the plugin:

it opens a window to select a palette as expected, then when I select a palette (for example one of the 3 bundled palettes that you have in the github download) there is no feedback once I select the palette and it does not appear inside my color palettes.

Thanks again for your help, I have attached a screen recording video to take you through the process so that you can see for yourself.

[ScreenRecording.zip](https://github.com/andrewfiorillo/sketch-palettes/files/370599/ScreenRecording.zip)

**Comment by ohcommon** [comment]
I have the same issue. Sketch version 39 (31667), mac 10.11.5.

**Comment by ideamonk** [comment]
I too have the same issue. - Sketch 39.

**Comment by andrewfiorillo** [comment]
I should have a fix coming a little later today for sketch 39, which was released today.

**Comment by andrewfiorillo** [comment]
I just pushed a fix for version v39. I'm going to close this issue since 3.8.3 won't be supported moving forward. There is a separate [issue](https://github.com/andrewfiorillo/sketch-palettes/issues/26) that specifically addresses the fix for the v39 update.

@mulvi If you still have problems after updating Sketch and the plugin, please let me know!
