### ISSUE TITLE
Create palette from list of Hex codes

### ISSUE THREAD

**Issue by miguelsolorio-zz** [andrewfiorillo/sketch-palettes#3]
It would awesome if there was a command for "Create Palette". You could provide an input dialog and ask the user to enter in the hex colors (comma separated) and then load those into the document colors. You can manually do this by modifying the exported .sketchpalette file but having this built-in would take it to the next level.

**Comment by andrewfiorillo** [comment]
I think this could be handy, but I'd really like to keep the plugin as simple and straightforward as possible. And since I have other features planned (like supporting other color formats, and global colors), I want to make sure the plugin and its menu don't get too complex.

It seems like you're savvy enough to just edit the file, but I could whip up a separate script for you to just do that if you're interested.

**Comment by miguelsolorio-zz** [comment]
In case anyone is interested, I added this functionality in [a forked version](https://github.com/miguelsolorio/sketch-palettes/) for the meantime. It only has the basic functionality, see commit 0e3a4a0efb0334cb93b51d403c5c741b6a776a77 for details.
