### ISSUE TITLE
Support transparent colors

### ISSUE THREAD

**Issue by andrewfiorillo** [andrewfiorillo/sketch-palettes#5]
Right now the plugin only supports hex colors, but it should support rgba colors as well, so transparency can be saved. Perhaps consider changing the storage format entirely to rgba. It would also need to maintain compatibility for palettes saved before rgba support.

**Comment by justinjaywang** [comment]
:+1:

**Comment by riddle** [comment]
Thanks for pointing me here.

> It would also need to maintain compatibility for palettes saved before rgba support.

Backwards compat is a neat idea but what if you didn’t? Then all people need to do is to export their palette into a new file and import that from now on. Should people want to open old files, they can just download old version of the plugin.

Bonus: the issue could move. I’m literally in a spot where I’m more likely to copy a screenshot of a palette around than import 88 colors and have to delete 44 because they were flattened.

Alternatively: do you run donations? 😄 Wink wink

**Comment by andrewfiorillo** [comment]
@riddle Sketch Palettes now supports transparent colors. Hope you find it useful!

**Comment by cecileboucheron** [comment]
Omg thank you!! Big thumbs up from the Keybase design team 👍
