### ISSUE TITLE
feature request: name colors

### ISSUE THREAD

**Issue by guylepage3** [andrewfiorillo/sketch-palettes#53]
So I've been thinking about this for a while now.. It would be super nice to be able to name my colors in sketch-palettes. Would save me quite a bit of time.

**Comment by andrewfiorillo** [comment]
I also would really love this ability, and it has been requested before. But until Sketch has some ability to assign and display names in the color picker, I think it is out of scope for this plugin. But if they add that ability, I'd eagerly add support for saving the names of each color/preset. For now, I'm going to close this issue, since this doesn't yet appear to be on their roadmap.

**Comment by andrewfiorillo** [comment]
Good news! In the forthcoming Sketch 53 release, support for naming colors will be added. So I will then be able to add the ability to save preset names with a palette. I'll be tracking it in this issue: https://github.com/andrewfiorillo/sketch-palettes/issues/74
