### ISSUE TITLE
Sketch palettes save not working

### ISSUE THREAD

**Issue by clisko** [andrewfiorillo/sketch-palettes#81]
Just installed the latest version of the plugin, but saving the palette does nothing. Also, there is no flyout menu for global colors and document colors, just save palette which does nothing as mentioned.

Sketch 52.6, MacOS Mojave.

Behavior is exactly the same as in this previous issue with loading palettes.

https://github.com/andrewfiorillo/sketch-palettes/issues/52

**Comment by Edsson88** [comment]
Same issue, same Sketch version, High Sierra.

**Comment by andrewfiorillo** [comment]
The latest version of the plugin does not work with older versions of Sketch. But, older versions of the plugin should work. You grab older versions of the plugin here:
https://github.com/andrewfiorillo/sketch-palettes/releases

However older versions of the plugin will of course not support saving names of presets, since that functionality didn't exist in older versions of Sketch.

**Comment by andrewfiorillo** [comment]
I'm going to go ahead and close this issue. But let me know if the older version of the plugin doesn't work for you.
