### ISSUE TITLE
I cant save a palette.

### ISSUE THREAD

**Issue by redg1402** [andrewfiorillo/sketch-palettes#82]
When i click "save palette" option nothing happens

**Comment by jcouturier** [comment]
Same issue, using Sketch v52.6 on macOS Mohave (10.14.3).

**Comment by x3us** [comment]
Same issue: Can't save or load palettes.
Sketch 52.5 on macOS High Sierra (10.13.6)

**Comment by stubbsy451** [comment]
The same issue for me, cannot save or load palettes.

Sketch v52.6, macOS Mojave 10.14.3

**Comment by pglevy** [comment]
Me three.

Sketch v52.6, macOS Mojave 10.14.3

**Comment by individual11** [comment]
Same here.

sketch 51.3, latest mojave

**Comment by andrewfiorillo** [comment]
Hello, sorry you are experiencing issues. It sounds like you are using an older version of Sketch. The plugin has since been updated for newer versions of Sketch and the latest version of the plugin won't work with versions of Sketch before v53. You should be able to use an older version of the plugin though. You can grab previous versions here: https://github.com/andrewfiorillo/sketch-palettes/releases
